name: channel_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.3
  # 网络请求组件
  dio: 4.0.4

  rxdart: 0.27.3

  # 以下是最新版本
  freezed_annotation: 1.0.0
  hive: 2.0.4
  # 缓存组件
  shared_preferences: 2.0.9
  # 图片缓存组件
  cached_network_image: 3.1.0
  # 系统路径组件
  path_provider: 2.0.5
  audioplayers: 0.20.1
  # 图片选择器组件
  image_picker: 0.8.4+2
  video_player: 2.2.5
  tuple: 2.0.0
  # ref: main
  # 处理Android 端网页无法打开网页问题
  flutter_inappwebview: 5.3.2
  # json动画解析组件
  lottie: 1.2.1
  injectable: 1.5.0
  json_annotation: 4.3.0

  get_it: 7.2.0
  photo_view: 0.13.0
  after_layout: 1.1.0
  package_info_plus: 1.0.6
  # 状态管理组件
  flutter_bloc: 7.3.3
  equatable: 2.0.3
  # 事件通信组件
  event_bus: 2.0.0
  # 加载框组件
  flutter_easyloading: 3.0.3
  # 吐司提示组件
  fluttertoast: 8.0.8
  # 验证码输入框组件
  pin_code_fields: 7.3.0
  # 二维码生成组件
  qr_flutter: 4.0.0
  # 微信组件
  fluwx: 3.6.1+2
  # 应用内升级组件
  ota_update: 3.1.0
  # 异常收集组件
  flutter_bugly: 0.3.3
  # 统计图组件
  # 选择器组件
  flutter_pickers: 2.1.4
  # 定位服务组件
  geolocator: 7.6.2
  url_launcher: 6.0.15
  # 屏幕适配组件
  flutter_screenutil: 5.0.0+2
  device_apps: 2.1.1
  jiffy: 4.1.0
  flutter_native_image: 0.0.6+1
  # 权限管理组件
  permission_handler: 8.1.6
  # 保存图片组件
  image_gallery_saver: 1.7.0
  infinite_scroll_pagination: 3.1.0
  # WiFi组件
  wifi_iot: 0.3.8
  logger: 1.1.0
  flutter_secure_storage: 5.0.2
  # 路由管理组件
  fluro: 2.0.3
  # 图片裁剪组件
  extended_image: 5.0.0
  # 轮播效果组件
  flutter_swiper_plus: 2.0.4
  image: 3.0.5
  # 网络状态监听组件
  connectivity_plus: 2.0.2
  # 设备信息组件
  device_info_plus: 3.0.1
  focus_detector: 2.0.0
  # 国际化
  intl: 0.17.0
  shimmer: 2.0.0
  # 骨架屏
  skeleton_text: 3.0.0
  xml: 5.3.0
  #  jpush_flutter: 2.1.7
  # 自动缩放字体
  auto_size_text: 3.0.0-nullsafety.0
  badges: 2.0.1
  uuid: 3.0.5
  # 海外第三方分享：Facebook , Instagram , Twitter等
  social_share: 2.2.1
  # 海外Facebook登录

  sign_in_with_apple: 3.3.0
  # 海外twitter登录
  #  twitter_login: 4.0.1
  # 海外google登录
  #  google_sign_in: 5.2.4

  #  date_format: 2.0.2
  #  upgrader:
  #  pedantic:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
